Surface error for render
GoogleContainerTools/skaffold pull request #4758
Opened 2020-09-02 22:06 UTC by nkubala

fixes https://github.com/GoogleContainerTools/skaffold/issues/4726

this error was getting swallowed because the same buffer used to capture the templated manifests output by helm was also capturing stderr in the case of a failure, which was getting thrown away.

2020-09-03 06:48 UTC, dgageot requested changes

2020-09-03 17:58 UTC, nkubala commented on pkg/skaffold/deploy/helm.go
> +			return fmt.Errorf(outBuffer.String())
good idea, fixed

2020-09-04 11:17 UTC, briandealwis approved these changes

2020-09-07 06:49 UTC, dgageot approved these changes

2020-09-09 17:17 UTC, merged