Adding distinct exit codes for Kubernetes connection failures.
GoogleContainerTools/skaffold pull request #4921
Opened 2020-10-16 16:30 UTC by PriyaModali

Fixes: #nnn 
**Related**: _Relevant tracking issues, for context_
**Merge before/after**: _Dependent or prerequisite PRs_

**Description**

**User facing changes (remove if N/A)**

**Follow-up Work (remove if N/A)**

2020-10-16 16:39 UTC, tejal29 requested changes
First draft looks good!
Please change the description of the PR to add details around
1. What bug it fixes. 
2. What are the output changes e.g. previous on master when connection failed the error was this.  On your branch the error shown is this. 
3. Add a test case in `errors_test.go`

2020-10-16 16:39 UTC, tejal29 commented on proto/skaffold.proto
> +    DEPLOY_CLUSTER_CONNECTION_ERR = 901;
Please add a comment above the the code 
```
// Deploy errors

// Cluster connection failure
DEPLOY_CLUSTER_CONNECTION_ERR = 901;

2020-10-16 16:39 UTC, tejal29 commented on pkg/skaffold/errors/errors.go
> +	for _, v := range knownDeployProblems {
you could drop repeating the loop by appending `knownBuildProblems` and `knownDeployProblems`
https://tour.golang.org/moretypes/15

2020-10-16 18:05 UTC, PriyaModali commented on proto/skaffold.proto
> +    DEPLOY_CLUSTER_CONNECTION_ERR = 901;
Added comment.

2020-10-20 18:08 UTC, tejal29 commented on pkg/skaffold/build/cache/retrieve.go
> -				return nil, fmt.Errorf("%s: %w", sErrors.PushImageErr, err)
this is an unintentional revert.

2020-10-20 18:10 UTC, tejal29 reviewed
I think your latest merge unintentionally reverted changes which should not be done.

2020-10-20 18:10 UTC, tejal29 commented on pkg/skaffold/docker/image.go
> -		return "", fmt.Errorf("%s %q: %w", sErrors.PushImageErr, ref, err)
This is an unintentional revert.

2020-10-20 18:10 UTC, tejal29 commented on pkg/skaffold/errors/buildProblems.go
> -	DockerConnectionFailed = ".*(Cannot connect to the Docker daemon.*) Is"
This is also an unintentional revert.

2020-10-23 20:25 UTC, tejal29 commented
please close this in favor of #4933

2020-10-24 04:24 UTC, closed without merging