`port-forward` should be able to select ports by service name
GoogleContainerTools/skaffold pull request #5009
Opened 2020-11-08 20:44 UTC by anshlykov

Fixes: #4464 

**Description**

This PR introduced the new type `IntOrString` and changed the type of `PortForwardResource.Port` to `IntOrString`. This change allows a named port or an int port to be used in the `kubectl port-forward ...` command.

Also, there are some breaking changes in the proto schema and changes in logging. I think this can be simply resolved but I have not done it yet because I want to validate my approach first (or maybe it is already OK)

2020-11-09 21:28 UTC, tejal29 requested changes
This change looks good to me except for the change in the skaffold.proto.
we have existing clients who use this event and changing `int` to `StringOrInt` may be break integration.

I will follow up with manually testing the new skaffold event on the CC IDEs side.

Meanwhile, can you instead use a new field and deprecate the existing field.

2020-11-09 21:28 UTC, tejal29 commented on proto/skaffold.proto
> +    IntOrString remotePort = 2; // remote port is the resource port that will be forwarded.
unfortunately, this will be a backward incompatible change.  Can we instead add a another field and mark this as deprecated.

2020-11-09 21:28 UTC, tejal29 commented on pkg/skaffold/event/event.go
> +				RemotePort: &proto.IntOrString{
Can we keep remote port as is if its of type int and use new field to populate the `intOrString` port value.

2020-11-12 18:11 UTC, tejal29 commented
@anshlykov Can you please rebase ? Would love to get this in before next release since we already merged the PR to upgrade skaffold config.

2020-11-13 11:04 UTC, anshlykov commented
I have rebased and added changes to the proto schema.

2020-11-13 16:02 UTC, tejal29 reviewed
LGTM. 

Pending Manual verification.

2020-11-19 00:17 UTC, tejal29 approved these changes
Manually verified this 
1. Integration test sample

2020-11-19 00:17 UTC, merged