Skaffold support for docker build '--squash' flag
GoogleContainerTools/skaffold pull request #5078
Opened 2020-11-28 02:38 UTC by rpunia7

Fixes: #5076  
**Related**: #5077 
**Merge before/after**: #5077 

**Description**

- added Skaffold support for docker build '--squash' flag

**TODO**
- err for gcb not supporting docker squash ?

2020-12-02 17:22 UTC, tejal29 requested changes
Thanks @rpunia7 . 
Can you please rebase your Pr and add unit tests to verify the `--squash` is added?

Thanks
Tejal

2020-12-03 17:06 UTC, rpunia7 commented
> Thanks @rpunia7 .
> Can you please rebase your Pr and add unit tests to verify the `--squash` is added?
> 
> Thanks
> Tejal

Thanks for the pointers @tejal29 , i'll update the PR soon.

2020-12-09 20:02 UTC, MarlonGamez commented
This looks good imo, should be able to merge if kokoro passes

2020-12-09 21:03 UTC, tejal29 approved these changes

2020-12-09 21:03 UTC, merged