Update codeowners
GoogleContainerTools/skaffold pull request #5213
Opened 2021-01-07 21:47 UTC by nkubala

in theory this was a good idea, but in practice it's causing wrong reviewers to be auto-added for any change that touches files in any of these subdirectories. let's just remove the github owners rules, and tag reviewers as needed for any domain-specific changes.

2021-01-07 21:54 UTC, gsquared94 approved these changes

2021-01-08 17:37 UTC, tejal29 commented
The JIB codeowners also helped the jib team to merge their PR without a review from skaffold-team right?

2021-01-08 17:40 UTC, tejal29 commented
> in theory this was a good idea, but in practice it's causing wrong reviewers to be auto-added for any change that touches files in any of these subdirectories. let's just remove the github owners rules, and tag reviewers as needed for any domain-specific changes.

you can also disable auto-code review [here] (https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/managing-code-review-assignment-for-your-team#:~:text=Disabling%20code%20review%20assignment,-In%20the%20top&text=name%2C%20click%20Teams.-,On%20the%20Teams%20tab%2C%20click%20the%20name%20of%20the%20team,Click%20Save%20changes.) instead.

I remember turning this on last year.

2021-01-08 17:44 UTC, tejal29 commented
I just did this for skaffold-team. If this does not take into effect, we can remove owners. 

![image](https://user-images.githubusercontent.com/1534539/104047050-dd514580-5195-11eb-85e3-a56dd7f5ed85.png)

2021-01-08 17:44 UTC, tejal29 requested changes
Do not merge.

2021-01-27 23:19 UTC, MarlonGamez commented
@tejal29 any update on this?

2021-02-23 21:37 UTC, closed without merging