Add digest source 'tag' to use tag without digest
GoogleContainerTools/skaffold pull request #5436
Opened 2021-02-22 12:59 UTC by fengye87

**Related**: #3649 

**Description**

A new option `skaffold render --digest-source=tag` was added, which will render the manifests with built tags. The difference between 'none' and 'tag' is that the former one will keep whatever artifacts are in the original manifests, while the latter will update them with proper tags, without sha256 digests.

This could be very helpful when rendering one-for-all release manifests in multi-arch deployment scenarios, although extra cares should be taken in this case to not move any released tags.

**User facing changes (remove if N/A)**

User gets a new option `skaffold render --digest-source=tag`

2021-02-25 00:44 UTC, tejal29 approved these changes

2021-02-25 17:58 UTC, MarlonGamez requested changes
This may be a dumb question but, what is the difference between using 'remote' vs 'tag'? Since they both go down the same code path now

2021-02-25 17:58 UTC, MarlonGamez commented on pkg/skaffold/runner/build_deploy.go
>  	// In dry-run mode or with --digest-source  set to 'remote', we don't build anything, just return the tag for each artifact.
```suggestion
	// In dry-run mode or with --digest-source  set to 'remote' or 'tag', we don't build anything, just return the tag for each artifact.
```

2021-02-25 19:21 UTC, MarlonGamez approved these changes
LGTM, just one nit to update the comment

2021-03-01 02:15 UTC, fengye87 commented
@tejal29 I've updated the comment as @MarlonGamez suggested, could you start another kokoro run please?

2021-03-04 20:22 UTC, merged