Update grpc.md
GoogleContainerTools/skaffold pull request #5461
Opened 2021-02-25 22:10 UTC by grmoon

**Description**
Update broken github link to `skaffold.proto`

2021-02-25 23:00 UTC, gsquared94 approved these changes

2021-02-25 23:45 UTC, MarlonGamez approved these changes
Thanks for this!

2021-02-25 23:50 UTC, MarlonGamez requested changes
grpc.md is actually generated from ./hack/generate-proto.sh. To make this change we should edit proto/v1/markdown.tmpl line 26 (and line 10 while we're at it) then generate the file again.

2021-02-26 18:28 UTC, MarlonGamez approved these changes

2021-02-26 18:28 UTC, merged