Reduce log level from Warning to Debug for unused artifacts in helm deploy
GoogleContainerTools/skaffold pull request #5468
Opened 2021-02-27 00:09 UTC by gsquared94

Fixes: #5455 

**Description**

The `helm` deployer displays a warning when a built artifact is not used in the deployment. Like:
```
WARN[0052] image [frontend:427522d4bb023a3b888c2d960e4456c6d5c56eea686a69e7065bdf8e2830a0d9] is not used. 
WARN[0052] image [frontend] is used instead.            
WARN[0052] See helm sample for how to replace image names with their actual tags: https://github.com/GoogleContainerTools/skaffold/blob/master/examples/helm-deployment/skaffold.yaml 
```

This warning is obsolete since `skaffold` now supports defining non-deployable artifacts like a `base` artifact, only used as another artifact's dependency. Also with multi config support, all artifacts are managed in the same flat list and passed along to every deployer. This triggers this warning for every helm deployment imported as a dependency.

However, removing this warning might also hide genuine error by the user in defining their `skaffold.yaml` file and not correctly linking the artifact image to a deployment `helm` chart.

I propose downgrading it to a debug level message; so that is is discoverable when trying to diagnose any issue.

2021-02-28 03:40 UTC, briandealwis commented
These warnings are useful: people get tripped up on them, especially when porting an existing project into Skaffold.  Until we ignore the tags, I don't think we should drop these warnings.

Maybe what we should do is teach the deployer here to consider image dependencies as a use.

2021-03-01 22:06 UTC, gsquared94 commented
we discussed this in the triage meeting and decided to improve the warning mechanism to only notify on images not used in the manifest by figuring out the list of required images from the manifest upfront. That would solve this issue. Closing this PR.

2021-04-08 17:27 UTC, gsquared94 commented
I want to reopen this with the following observations:
- This warning didn't always make sense even in pre-multiconfig era of Skaffold. Consider a single `skaffold.yaml` with an artifact with a corresponding `kubectl` deployer; and a `helm` deployer that sets up a database. During this helm chart deployment skaffold will show this warning even though the artifact is used in another deployer.
- With multiconfig and build dependencies support, we can't reliably say if any artifact needs to be a part of the helm chart. Skaffold supports deploying remote charts which don't need any artifacts.
- We can parse the helm templates to find container specs that are templated on `{{.Values.image}}` and but not providing any `artifactOverrides` in the `skaffold.yaml`. But that doesn't rely on the artifact list, so this `Warn` needs to go 🙂

2021-04-21 05:17 UTC, tejal29 commented
So, I ended up resurrecting a usecase for which the warning was introduced. 
```
diff --git a/examples/helm-deployment/charts/values.yaml b/examples/helm-deployment/charts/values.yaml
index ba42ad6e1..be55ebdad 100644
--- a/examples/helm-deployment/charts/values.yaml
+++ b/examples/helm-deployment/charts/values.yaml
@@ -2,3 +2,4 @@
 # This is a YAML-formatted file.
 # Declare variables to be passed into your templates.
 replicaCount: 2
+image: gcr.io/kaniko-project/executor:latest
diff --git a/examples/helm-deployment/skaffold.yaml b/examples/helm-deployment/skaffold.yaml
index fcbf144ac..2d2dff587 100644
--- a/examples/helm-deployment/skaffold.yaml
+++ b/examples/helm-deployment/skaffold.yaml
@@ -8,5 +8,3 @@ deploy:
     releases:
     - name: skaffold-helm
       chartPath: charts
-      artifactOverrides:
-        image: skaffold-helm
 ```

I see the warning in this flow.
```
WARN[0007] image [gcr.io/tejal-gke1/skaffold-helm:v1.21.0-5-g8b4cfdae3-dirty@sha256:14b6a7b7b4112159117be7f5f7867379acf8286e83eb7df0b318027a6b3766ab] is not used. 
WARN[0007] image [skaffold-helm] is used instead.       
WARN[0007] See helm sample for how to replace image names with their actual tags: https://github.com/GoogleContainerTools/skaffold/blob/master/examples/helm-deployment/skaffold.yaml 
```

However, there are two issues here
1) The helm sample example link is not at all informative and we should point to the docs here https://skaffold.dev/docs/pipeline-stages/deployers/helm/#image-configuration
2) Not sure why my default repo got wiped out. It should probably say the `gcr.io/kaniko-project/executor:latest` is being used.
Looking at the code, it plainly uses the value in `artifacts.image[0]`
Maybe this side-effect was introduced when  `ArtifactGraph` was added or even before that. 

It would makes sense to 
1) Remove `image ** is used` warning line since it is incorrect.
2) Update the document link.

Regarding @briandealwis's point. Yes, if i did not have that warning it would be hard for me to debug.
How about we only show the warning if 
1) len(deployers) is 1 and len(skaffold) pipelines is 1?

Another approach is to add another field to `Artifact` similar to `IsBase`. Skip showing unused warnings for base artifacts as they may or may not be part of deployment.

2021-04-21 05:19 UTC, tejal29 requested changes
Few suggestions to keep the warning only if helm deployer is used in single skaffold config.

2021-04-22 00:18 UTC, gsquared94 commented
> Few suggestions to keep the warning only if helm deployer is used in single skaffold config.

Implemented suggestions. PTAL @tejal29

2021-04-22 18:46 UTC, tejal29 approved these changes

2021-04-22 18:46 UTC, merged