typo-fix
GoogleContainerTools/skaffold pull request #5772
Opened 2021-05-03 17:53 UTC by aleksandrOranskiy

Fixes: #nnn 
**Related**: _Relevant tracking issues, for context_
**Merge before/after**: _Dependent or prerequisite PRs_

**Description**
It's just a small typo fix.

**User facing changes (remove if N/A)**

**Follow-up Work (remove if N/A)**

2021-05-03 21:50 UTC, nkubala requested changes
@aleksandrOranskiy thanks for the fix! would you mind signing our CLA using the email you used to make this commit? i'll retrigger our integration tests to get CI green on here and then we can get this merged

2021-05-03 21:50 UTC, nkubala commented on docs/content/en/docs/pipeline-stages/builders/custom.md
> +To configure custom build script in cluster, in addition to adding a [`custom` field](#configuration) to each corresponding artifact in the `build`, add `cluster` to you `build` config.
:) 
```suggestion
To configure custom build script in cluster, in addition to adding a [`custom` field](#configuration) to each corresponding artifact in the `build`, add `cluster` to your `build` config.
```

2021-05-04 08:04 UTC, aleksandrOranskiy commented
@googlebot I signed it!

2021-05-05 23:50 UTC, MarlonGamez approved these changes
lgtm! Thanks @aleksandrOranskiy :)

2021-05-05 23:51 UTC, merged