Expose --event-log-file to render, apply, and test
GoogleContainerTools/skaffold pull request #5828
Opened 2021-05-12 22:05 UTC by briandealwis

Related to: #5125

**Description**
#5125 added the ability to log events to a file for `dev`, `build`, `run`, `debug`, `deploy`.  It would be useful to have this available for `render`, `apply`, and `test`.

This PR adds `--event-log-file` and `--enable-rpc` for `render`, `apply`, and `test`.

**Follow-up Work (remove if N/A)**
- it would be useful to remove the requirement to also run `--enable-rpc`
- integration tests to ensure that this flag is available as partners may rely on it

2021-05-12 22:36 UTC, aaron-prindle commented
Code change LGTM, I believe doc generation needs to be re-run here - `./hack/generate-man.sh`.  From travis logs
```
/hack/man/TestPrintMan
    man_test.go:52: You have skaffold command changes but haven't generated the CLI reference docs. Please run ./hack/generate-man.sh and commit the results!
```

2021-05-13 13:16 UTC, briandealwis commented
Docs regenerated @aaron-prindle

2021-05-13 16:34 UTC, aaron-prindle approved these changes
LGTM

2021-05-13 17:18 UTC, tejal29 requested changes
Mark the flag hidden.

2021-05-13 18:16 UTC, briandealwis commented
Flag is now hidden.

2021-05-13 18:54 UTC, nkubala approved these changes
LGTM, I restarted the flaked CI job but feel free and merge when green

2021-05-13 19:10 UTC, merged