feat: add dockerfile support to skaffold lint and top 2 dockerfile rules
GoogleContainerTools/skaffold pull request #6793
Opened 2021-11-02 23:23 UTC by aaron-prindle

fixes #6103 by adding 2 dockerfile lint rules:
- DockerfileCopyOver1000Files
- DockerfileCopyContainsGitDir

The rules have the following output when triggered (note `skaffold lint` is run against modified version of `examples/microservices` here w/ misconfigurations added to the Dockerfiles, not the actual `examples/microservices`):
```
$ skaffold lint
leeroy-web/Dockerfile:3:1: ID000005: DockerfileCommandLintRule: Found 'COPY . .', where the source dir: "." contains a '.git' directory at /usr/local/google/home/aprindle/lint-samples/leeroy-web/.git.  This has the potential to dramatically slow 'skaffold dev' down as skaffold whill watch all of the files in the .git directory as skaffold watches all sources files referenced in dockerfile COPY directives for changes. skaffold will likely rebuild images unnecessarily when non-image-critical files are modified during any git related operation. Consider adding a .dockerignore file (https://docs.docker.com/engine/reference/builder/#dockerignore-file) removing the '.git' directory. skaffold respects files ignored via the .dockerignore
COPY . .
^
leeroy-app/Dockerfile:3:1: ID000004: DockerfileCommandLintRule: Found 'COPY . .', where the source dir: "." has over 1000 files.  This has the potential to dramatically slow 'skaffold dev' down as skaffold watches all sources files referenced in dockerfile COPY directives for changes. If you notice skaffold rebuilding images unnecessarily when non-image-critical files are modified, consider changing this to 'COPY $REQUIRED_SOURCE_FILE(s) .' for each required source file instead of or adding a .dockerignore file (https://docs.docker.com/engine/reference/builder/#dockerignore-file) ignoring non-image-critical files.  skaffold respects files ignored via the .dockerignore
COPY . .
^

```

2021-11-03 00:03 UTC, MarlonGamez reviewed
did a very quick pass on this and just have some nits, will take a deeper look and comb through the logic more

2021-11-03 00:05 UTC, aaron-prindle commented on pkg/skaffold/lint/linters.go
> +	log.Entry(context.TODO()).Errorf("params.ConfigFile.Text: %s", params.ConfigFile.Text)
Accidentally left this from debugging, fixed now.  Thanks!

2021-11-03 00:05 UTC, aaron-prindle commented on pkg/skaffold/lint/linters.go
> +	log.Entry(context.TODO()).Errorf("parser.Parse(strings.NewReader(params.ConfigFile.Text)) had err: %v", err)
Accidentally left this from debugging, fixed now. Thanks!

2021-11-03 00:05 UTC, aaron-prindle commented on pkg/skaffold/lint/linters.go
> +// ===================
removed

2021-11-03 00:06 UTC, aaron-prindle commented on pkg/skaffold/lint/types.go
>  type InputParams struct {
done

2021-11-03 16:09 UTC, MarlonGamez requested changes

2021-11-03 16:09 UTC, MarlonGamez commented on pkg/skaffold/lint/dockerfiles.go
> +			`as skaffold whill watch all of the files in the .git directory as skaffold watches all sources files referenced in dockerfile COPY directives for changes. ` +
```suggestion
			`as skaffold will watch all of the files in the .git directory as skaffold watches all sources files referenced in dockerfile COPY directives for changes. ` +
```

2021-11-03 16:09 UTC, MarlonGamez commented on pkg/skaffold/lint/dockerfiles_test.go
> +							`This has the potential to dramatically slow 'skaffold dev' down as skaffold whill watch all of the files in the .git ` +
```suggestion
							`This has the potential to dramatically slow 'skaffold dev' down as skaffold will watch all of the files in the .git ` +
```

2021-11-03 18:23 UTC, aaron-prindle commented on pkg/skaffold/lint/dockerfiles_test.go
> +							`This has the potential to dramatically slow 'skaffold dev' down as skaffold whill watch all of the files in the .git ` +
done

2021-11-03 18:23 UTC, aaron-prindle commented on pkg/skaffold/lint/dockerfiles.go
> +			`as skaffold whill watch all of the files in the .git directory as skaffold watches all sources files referenced in dockerfile COPY directives for changes. ` +
done

2021-11-04 21:17 UTC, MarlonGamez commented
Found a bug when testing locally, not completely sure what's happening though. Seems like the lint condition is firing when it shouldn't be 

Output: 
```
❯ skaf-dev lint
/skaffold.yaml:3:13: ID000001: YamlFieldLintRule: Found 'apiVersion' field with value that is not the latest skaffold apiVersion. Modify the apiVersion to the latest version: `apiVersion: skaffold/v2beta25` or run the 'skaffold fix' command to have skaffold upgrade this for you.
apiVersion: skaffold/v2beta4
            ^
/skaffold.yaml:19:1: ID000002: YamlFieldLintRule: It is a skaffold best practice to specify a static port (vs skaffold dynamically choosing one) for port forwarding container based resources skaffold deploys.  This is helpful because wit this the local ports are predictable across dev sessions which  makes testing/debugging easier. It is recommended to add the following stanza at the end of your skaffold.yaml for each shown deployed resource:
portForward:
- resourceType: deployment
  resourceName: go-hello-world
  port: 8080
  localPort: 32581

^
Dockerfile:9:1: ID000005: DockerfileCommandLintRule: Found 'COPY go.mod .', where the source dir: "go.mod" contains a '.git' directory at /Users/marlongamez/Projects/go-hello-world/.git.  This has the potential to dramatically slow 'skaffold dev' down as skaffold will watch all of the files in the .git directory as skaffold watches all sources files referenced in dockerfile COPY directives for changes. skaffold will likely rebuild images unnecessarily when non-image-critical files are modified during any git related operation. Consider adding a .dockerignore file (https://docs.docker.com/engine/reference/builder/#dockerignore-file) removing the '.git' directory. skaffold respects files ignored via the .dockerignore
COPY go.mod go.sum ./
^
Dockerfile:9:1: ID000005: DockerfileCommandLintRule: Found 'COPY go.sum .', where the source dir: "go.sum" contains a '.git' directory at /Users/marlongamez/Projects/go-hello-world/.git.  This has the potential to dramatically slow 'skaffold dev' down as skaffold will watch all of the files in the .git directory as skaffold watches all sources files referenced in dockerfile COPY directives for changes. skaffold will likely rebuild images unnecessarily when non-image-critical files are modified during any git related operation. Consider adding a .dockerignore file (https://docs.docker.com/engine/reference/builder/#dockerignore-file) removing the '.git' directory. skaffold respects files ignored via the .dockerignore
COPY go.mod go.sum ./
^
Dockerfile:13:1: ID000005: DockerfileCommandLintRule: Found 'COPY . .', where the source dir: "." contains a '.git' directory at /Users/marlongamez/Projects/go-hello-world/.git.  This has the potential to dramatically slow 'skaffold dev' down as skaffold will watch all of the files in the .git directory as skaffold watches all sources files referenced in dockerfile COPY directives for changes. skaffold will likely rebuild images unnecessarily when non-image-critical files are modified during any git related operation. Consider adding a .dockerignore file (https://docs.docker.com/engine/reference/builder/#dockerignore-file) removing the '.git' directory. skaffold respects files ignored via the .dockerignore
COPY . ./
^
Dockerfile:31:1: ID000005: DockerfileCommandLintRule: Found 'COPY template /template', where the source dir: "template" contains a '.git' directory at /Users/marlongamez/Projects/go-hello-world/.git.  This has the potential to dramatically slow 'skaffold dev' down as skaffold will watch all of the files in the .git directory as skaffold watches all sources files referenced in dockerfile COPY directives for changes. skaffold will likely rebuild images unnecessarily when non-image-critical files are modified during any git related operation. Consider adding a .dockerignore file (https://docs.docker.com/engine/reference/builder/#dockerignore-file) removing the '.git' directory. skaffold respects files ignored via the .dockerignore
COPY template ./template
^

```

My project directory looks like this:
```
.
├── .git
├── Dockerfile
├── README.md
├── curl-out
├── go.mod
├── go.sum
├── img
│   ├── create-k8s-cluster.png
│   ├── deploy-config.png
│   ├── deploy-success.png
│   ├── diagram.png
│   ├── edit-configurations.png
│   ├── image-repo.png
│   ├── kubernetes-url.png
│   ├── run-debug-dialog.png
│   └── status-bar.png
├── kubernetes-manifests
│   ├── hello.deployment.yaml
│   └── hello.service.yaml
├── main.go
├── skaffold.yaml
└── template
    ├── index.html
    └── static
        ├── KE-hello-world-dark.svg
        ├── KE-hello-world.svg
        ├── cloud_bg.svg
        ├── dark_bg.svg
        ├── kubernetes-engine-icon.png
        └── lightbulb_icon.svg
```

It seems to be firing the .git copy error on files such as `go.mod`, `go.sum`, and the directory `template/`

2021-11-08 06:20 UTC, aaron-prindle commented
> Found a bug when testing locally, not completely sure what's happening though. Seems like the lint condition is firing when it shouldn't be.

Thanks for finding this issue, this is related to the lint logic treating a Dockerfile's deps accidentally as all of the deps for each COPY command versus mapping COPY command-> specific deps.  What happened above is that **each** COPY command was flagged as a lint error when actually it was supposed to only the single `COPY . <DEST>` command.  This is fixed now and the unit tests now cover this case explicitly.

2021-11-08 21:51 UTC, MarlonGamez approved these changes
LGTM ✅ Thanks for addressing the commenets/issues. Looks like merge conflicts just need to be fixed then this should be good to merge

2021-11-09 18:16 UTC, merged