add --- in the beginning
GoogleContainerTools/skaffold pull request #7795
Opened 2022-08-23 11:02 UTC by lyra95

Fixes: #7793 
**Related**: _Relevant tracking issues, for context_
**Merge before/after**: _Dependent or prerequisite PRs_

**Description**

Running `skaffold render` triggers `helm template --post-renderer=skaffold`, and skaffold post-render the `helm template` output via hidden command `skaffold filter`.

However, output of `skaffold filter` is missing `---` at the beginning, which cause a bug when `skaffold.yaml` contains at least 2 helm charts.

**User facing changes (remove if N/A)**

**Follow-up Work (remove if N/A)**

2022-08-23 19:27 UTC, tejal29 commented
@lyra95 can you for the change. 
Do you think we should make this change to `manifests.ToString` instead? https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/kubernetes/manifest/manifests.go#L65

2022-08-23 21:18 UTC, tejal29 commented
Related or also fixes #7796

2022-08-24 02:14 UTC, lyra95 commented
> @lyra95 can you for the change. 
> 
> Do you think we should make this change to `manifests.ToString` instead? https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/kubernetes/manifest/manifests.go#L65

I agree

2022-08-24 05:12 UTC, lyra95 commented
https://github.com/GoogleContainerTools/skaffold/blob/main/cmd/skaffold/app/cmd/dev_test.go#L72 I'm failing on this test.
I can see the intention of the test, but I'm not sure how to fix it.
Should I change test suits or change the condition https://github.com/GoogleContainerTools/skaffold/blob/main/cmd/skaffold/app/cmd/dev.go#L75

2022-08-24 07:24 UTC, gsquared94 commented
The correct place to make this change is in the helm renderer. You can apply this patch:
```diff
diff --git a/pkg/skaffold/render/renderer/helm/helm.go b/pkg/skaffold/render/renderer/helm/helm.go
index 52fc0043f..471fa7f2d 100644
--- a/pkg/skaffold/render/renderer/helm/helm.go
+++ b/pkg/skaffold/render/renderer/helm/helm.go
@@ -97,7 +97,7 @@ func (h Helm) Render(ctx context.Context, out io.Writer, builds []graph.Artifact
 }
 
 func (h Helm) generateHelmManifests(ctx context.Context, builds []graph.Artifact) (manifest.ManifestList, error) {
-	renderedManifests := new(bytes.Buffer)
+	var renderedManifests manifest.ManifestList
 	helmEnv := sUtil.OSEnviron()
 	var postRendererArgs []string
 
@@ -146,14 +146,10 @@ func (h Helm) generateHelmManifests(ctx context.Context, builds []graph.Artifact
 		if err := helm.Exec(ctx, h, outBuffer, false, helmEnv, args...); err != nil {
 			return nil, helm.UserErr("std out err", fmt.Errorf(outBuffer.String()))
 		}
-		renderedManifests.Write(outBuffer.Bytes())
-	}
-	manifests, err := manifest.Load(bytes.NewReader(renderedManifests.Bytes()))
-	if err != nil {
-		return nil, err
+		renderedManifests.Append(outBuffer.Bytes())
 	}
 
-	manifests, err = manifests.SetLabels(h.labels, manifest.NewResourceSelectorLabels(h.transformAllowlist, h.transformDenylist))
+	manifests, err := renderedManifests.SetLabels(h.labels, manifest.NewResourceSelectorLabels(h.transformAllowlist, h.transformDenylist))
 	if err != nil {
 		return nil, err
 	}
```

2022-08-24 07:31 UTC, gsquared94 requested changes
https://github.com/GoogleContainerTools/skaffold/pull/7795#issuecomment-1225304208

2022-08-24 07:54 UTC, lyra95 commented
@gsquared94 Thanks. I've confirmed your fix solves my issue.

2022-08-24 15:51 UTC, gsquared94 approved these changes

2022-08-24 16:16 UTC, merged