Feat: retry copy context in order to avoid possible network failures
GoogleContainerTools/skaffold pull request #7887
Opened 2022-09-25 14:21 UTC by santinoncs

* If we add a for loop and execute the kubectlcli.Run method for copying context to kaniko pod , this makes more reliable and less prune to network failures

2022-10-03 18:56 UTC, aaron-prindle commented on pkg/skaffold/build/cluster/kaniko.go
> +	attemptMax := 3
nit: can you make this a `const` and put it at the top of the file?  Thanks

2022-10-03 18:57 UTC, aaron-prindle commented
Thanks for the PR @santinoncs, left one nit comment.  Once we resolve that we should be able to merge

2022-10-04 13:10 UTC, santinoncs commented
> Thanks for the PR @santinoncs, left one nit comment. Once we resolve that we should be able to merge

thanks!
done

2022-10-07 19:49 UTC, tejal29 requested changes
This change looks good to me.  However can we change the implementation to wire backoff mechanism like elsewhere in the code?

https://github.com/GoogleContainerTools/skaffold/blob/34f48f7f60ab583d49777caf14802200e39035b6/pkg/skaffold/docker/logger/log.go#L132

This will ensure, the code waits before the next attempt.

2022-10-11 01:39 UTC, aaron-prindle commented
Seems there is linter error preventing merge atm:
```
kg/skaffold/build/cluster/kaniko.go:147: unnecessary trailing newline (whitespace)

	}
FAILED hack/golangci-lint.sh
```
I think you you remove that newline we can merge 🎊

2022-10-14 04:26 UTC, tejal29 approved these changes

2022-10-18 16:36 UTC, santinoncs commented
can we merge? thanks!

2022-10-25 16:29 UTC, santinoncs commented
Hi @tejal29 

is there any reason we cannot merge this? sorry and thank you!

2022-11-03 18:41 UTC, aaron-prindle commented
Sorry for the delay @santinoncs, merging this now.  Thanks for the fix!

2022-11-03 18:41 UTC, merged