feat: allow ValuesFile from GCS
GoogleContainerTools/skaffold pull request #9182
Opened 2023-11-20 09:26 UTC by ashokhein

Fixes: #9172  

**Description**
Allow to reference the ValuesFile from Google Storage Bucket.  It uses the gsutil to copy the remote file and, put it in the temporary directory and reference it in the helm flags.

2024-01-22 22:30 UTC, ashokhein commented
@JeromeJu can you review this one?

2024-09-24 09:17 UTC, asubramanianrl commented
@JeromeJu can you review this one? Please let me know if any other action is to be taken care.

2024-09-24 09:42 UTC, ashokhein commented
[@JeromeJu](https://github.com/JeromeJu) can you review this one? Please let me know if any other action is to be taken care.

2024-11-15 14:46 UTC, mepi262 commented
@plumpy 
Would you review this pull request?

2024-12-28 15:00 UTC, mepi262 commented
@idsulik @tejal29 @nathanperkins @menahyouyeah @briandealwis @louisjimenez @plumpy @ChrisGe4 @alphanota @johannespfrang @katiexzhang @mattsanta @gsquared94
Would someone review this pull request?

2024-12-28 15:10 UTC, idsulik commented on pkg/skaffold/helm/args.go
> +		tempValueFile := v
there is no point to create this var here, you can create it on the 108 line

2024-12-28 15:11 UTC, idsulik commented on pkg/skaffold/helm/args.go
> +			tempDir, err := os.MkdirTemp("", valueFileFromGCS)
the condition's body can be extracted for better readability

2024-12-28 15:11 UTC, idsulik commented on pkg/skaffold/helm/args.go
> +			if err := gcs.Copy(context.Background(), v, tempValueFile, false); err != nil {
why `context.Background()`, but not `TODO()`?

2024-12-28 15:15 UTC, idsulik commented on pkg/skaffold/helm/args.go
> +		if strings.HasPrefix(v, gcsPrefix) {
it looks like it'll be better to contribute to the helm repository

2025-02-03 12:43 UTC, ashokhein commented on pkg/skaffold/helm/args.go
> +		if strings.HasPrefix(v, gcsPrefix) {
Skaffold has already been integrated with GCP, so I thought to make the change here.

2025-02-03 12:43 UTC, ashokhein commented on pkg/skaffold/helm/args.go
> +			if err := gcs.Copy(context.Background(), v, tempValueFile, false); err != nil {
I updated to `TODO() `as it requires the context temporarily

2025-02-03 12:44 UTC, ashokhein commented on pkg/skaffold/helm/args.go
> +			tempDir, err := os.MkdirTemp("", valueFileFromGCS)
Thanks for the suggestion, yes separated to the new function.

2025-02-10 21:45 UTC, ashokhein commented
@idsulik can you review this?

2025-02-11 04:58 UTC, idsulik commented on pkg/skaffold/helm/args.go
> +	if err := gcs.Copy(context.TODO(), v, tempValueFile, false); err != nil {
need to pass real context

2025-02-11 04:59 UTC, idsulik commented
@ashokhein I did it, you need to wait for the maintainers

2025-03-14 10:27 UTC, ashokhein commented
@Darien-Lin Can you please review this code?

2025-03-14 18:34 UTC, Darien-Lin commented
Can you add tests for this?

2025-03-17 14:03 UTC, Darien-Lin requested changes
Thank you for adding the tests. I have started the presubmits for this PR. 
Can you please address the linting issues found by the linter? Thanks for the contribution!

2025-03-18 10:10 UTC, asubramanianrl commented
> Thank you for adding the tests. I have started the presubmits for this PR. Can you please address the linting issues found by the linter? Thanks for the contribution!

I fixed that linting issue.  Thank you.

2025-03-18 10:13 UTC, ashokhein commented
> Thank you for adding the tests. I have started the presubmits for this PR. Can you please address the linting issues found by the linter? Thanks for the contribution!

I fixed that linting issue. Thank you.

2025-03-18 15:35 UTC, merged